# ControlPlane — the four reproduction tiers. Block E, E.4.
#
#   make smoke     CPU, no network, < 60s   the clone works and the package imports
#   make test      CPU, ~10 min             549 tests green
#   make verify    CPU (+cache for tier 3)  every claim reproduces and every metric recomputes
#   make extract   GPU, ~1 h                activations regenerate from the source model
#
# Every target exits non-zero on failure. `verify` exits non-zero if any number
# drifts from the artifact that produced it.
#
# Every recipe is a single command with no shell logic in it, so each target has
# an exact equivalent for anyone without make -- Windows, most often. The README
# lists them beside these. A Makefile that is the only way to run the project is
# a dependency the project does not need.

PYTHON ?= python

.DEFAULT_GOAL := help
.PHONY: help smoke test verify verify-claims extract

help:
	@$(PYTHON) -c "print(open('Makefile', encoding='utf-8').read().split('PYTHON ?=')[0])"

smoke:
	$(PYTHON) scripts/smoke.py

test:
	$(PYTHON) -m pytest tests/ -q

verify:
	$(PYTHON) scripts/verify.py

verify-claims:
	$(PYTHON) scripts/verify.py --claims-only

# Nobody will run this. Documented so the chain from raw model to published
# number has no gap in it. Needs a 16 GB GPU and about an hour, and downloads
# Qwen2.5-7B-Instruct. The tested path is notebooks/run_on_kaggle.ipynb,
# generated by scripts/build_notebooks.py.
extract:
	$(PYTHON) scripts/00_extract.py --config config.yaml
