"""Push the extraction notebook to Kaggle as a batch kernel, and collect it.

Thin orchestration around the ``kaggle`` CLI: no measurement logic lives here,
and the notebook it pushes is generated by ``build_notebooks.py``.

**Batch, not interactive.** A push starts a fresh headless session that runs the
notebook top to bottom and saves whatever lands in ``/kaggle/working``. There is
no attach and no cell-by-cell execution, so this cannot reach a session already
open in a browser or read a value out of its memory.

The CLI has no cancel verb, so a run started here is stopped from the web UI.
That asymmetry is why ``push`` requires ``--yes``: starting costs GPU quota
(30 h/week free tier, ~3.2 h measured for this extraction) and cannot be undone
from the terminal.

Usage:
    python scripts/kaggle_run.py push --yes [--accelerator "nvidiaTeslaT4"]
    python scripts/kaggle_run.py status
    python scripts/kaggle_run.py logs
    python scripts/kaggle_run.py fetch --out results/kaggle
    python scripts/kaggle_run.py wait --out results/kaggle
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path
from typing import Optional

PROJECT = Path(__file__).resolve().parent.parent
UPLOAD = PROJECT / "kaggle"
NOTEBOOK = PROJECT / "notebooks" / "run_on_kaggle.ipynb"
METADATA = UPLOAD / "kernel-metadata.json"

# Terminal states reported by `kaggle kernels status`. Anything else means the
# run is still going; treating an unknown string as finished would report a
# half-run kernel as a result.
DONE = ("complete", "error", "cancelAcknowledged", "cancelRequested")


def _cli(*args: str, check: bool = True) -> subprocess.CompletedProcess:
    """Run the kaggle CLI through this interpreter, so the venv's copy is used."""
    command = [sys.executable, "-m", "kaggle", *args]
    result = subprocess.run(command, capture_output=True, text=True)
    if check and result.returncode != 0:
        raise SystemExit(
            "kaggle CLI failed: %s\n%s\n%s"
            % (" ".join(args), result.stdout.strip(), result.stderr.strip())
        )
    return result


def _kernel_id() -> str:
    """The kernel's ``owner/slug``, with the username filled in if templated."""
    metadata = json.loads(METADATA.read_text(encoding="utf-8"))
    kernel_id = metadata["id"]
    if kernel_id.startswith("KAGGLE_USERNAME/"):
        username = os.environ.get("KAGGLE_USERNAME")
        if not username:
            raise SystemExit(
                "kaggle/kernel-metadata.json still has the KAGGLE_USERNAME "
                "placeholder. Put your Kaggle username in the 'id' field, or "
                "export KAGGLE_USERNAME."
            )
        kernel_id = kernel_id.replace("KAGGLE_USERNAME", username, 1)
        metadata["id"] = kernel_id
        METADATA.write_text(json.dumps(metadata, indent=2) + "\n", encoding="utf-8")
    return kernel_id


def push(accelerator: Optional[str], timeout: Optional[int], yes: bool) -> None:
    """Copy the generated notebook into the upload folder and start a run."""
    if not yes:
        raise SystemExit(
            "refusing to push without --yes. A run consumes GPU quota (~3.2 h "
            "measured) and the CLI has no cancel verb, so it can only be "
            "stopped from the web UI."
        )
    if not NOTEBOOK.exists():
        raise SystemExit(
            f"{NOTEBOOK} does not exist. Run scripts/build_notebooks.py first; "
            "the notebook is generated, never hand-edited."
        )
    kernel_id = _kernel_id()
    shutil.copy2(NOTEBOOK, UPLOAD / "run_on_kaggle.ipynb")
    args = ["kernels", "push", "-p", str(UPLOAD)]
    if accelerator:
        args += ["--accelerator", accelerator]
    if timeout:
        args += ["-t", str(timeout)]
    result = _cli(*args)
    print(result.stdout.strip() or result.stderr.strip())
    print("started %s -- poll with: python scripts/kaggle_run.py status" % kernel_id)


def status() -> str:
    """Print and return the latest run's status string."""
    result = _cli("kernels", "status", _kernel_id())
    text = (result.stdout or result.stderr).strip()
    print(text)
    return text


def logs() -> None:
    result = _cli("kernels", "logs", _kernel_id(), check=False)
    print((result.stdout or result.stderr).strip())


def fetch(out: Path) -> None:
    """Download the run's output files."""
    out.mkdir(parents=True, exist_ok=True)
    result = _cli("kernels", "output", _kernel_id(), "-p", str(out))
    print((result.stdout or result.stderr).strip())
    for path in sorted(out.rglob("*")):
        if path.is_file():
            print("  %s  %.1f MiB" % (path, path.stat().st_size / 2**20))


def wait(out: Optional[Path], poll_seconds: int) -> None:
    """Poll until the run reaches a terminal state, then fetch if asked.

    Polls rather than streams because the API exposes no push notification. The
    interval is deliberately slack: the run takes hours, and a tight loop only
    burns API quota.
    """
    while True:
        text = status().lower()
        if any(state.lower() in text for state in DONE):
            break
        time.sleep(poll_seconds)
    logs()
    if out is not None:
        fetch(out)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)

    push_parser = sub.add_parser("push", help="upload and start a run")
    push_parser.add_argument("--yes", action="store_true", help="confirm the quota cost")
    # Case-sensitive, and the server neither validates nor reports an
    # unrecognised value: it silently falls back to enable_gpu, which is a
    # P100. A P100 is sm_60, below this PyTorch build's sm_70 floor, and
    # bitsandbytes has no sm_60 NF4 kernel -- so the run dies two minutes in
    # with "named symbol not found". Read off a kernel that ran on T4 x2
    # (kaggle kernels pull -m) rather than guessed.
    push_parser.add_argument("--accelerator", default="NvidiaTeslaT4")
    push_parser.add_argument("--timeout", type=int, default=None)

    sub.add_parser("status", help="latest run status")
    sub.add_parser("logs", help="latest run logs")

    fetch_parser = sub.add_parser("fetch", help="download outputs")
    fetch_parser.add_argument("--out", type=Path, default=PROJECT / "results" / "kaggle")

    wait_parser = sub.add_parser("wait", help="poll to completion, then fetch")
    wait_parser.add_argument("--out", type=Path, default=PROJECT / "results" / "kaggle")
    wait_parser.add_argument("--poll-seconds", type=int, default=300)

    args = parser.parse_args()
    if args.command == "push":
        push(args.accelerator, args.timeout, args.yes)
    elif args.command == "status":
        status()
    elif args.command == "logs":
        logs()
    elif args.command == "fetch":
        fetch(args.out)
    elif args.command == "wait":
        wait(args.out, args.poll_seconds)


if __name__ == "__main__":
    main()
